config/routes.rb
Rails.application.routes.draw do
  resources :visitantes
  resources :contactos, only: [:new, :create]
  root to:'visitantes#index'

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
	has_no_table

	attr_accessor :nombre, :string
	attr_accessor :email, :string
	attr_accessor :mensaje, :string

	validates_presence_of :nombre
	validates_presence_of :email
	validates_presence_of :mensaje
	validates_format_of :email, :with => /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates_length_of :mensaje, :maximum => 500
end

app/models/visitante.rb
class Visitante < ActiveRecord::Base
has_no_table

attr_accessor :email, :string

 validates_presence_of :email
 validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

#column :nombre, :string

def nombre
     nombre = "Calo"
end


def fechacumple
    $fechacumple= Date.new(1994, 7, 9)
end

def conteo
    Rails.logger.debug 'DEBUG: Entrando en el método conteo del modelo de visitante'

  hoy= Date.today
  $fechacumple= Date.new(hoy.year, $fechacumple.month, $fechacumple.day)
  if $fechacumple > hoy
    conteo = ($fechacumple - hoy).to_i
  else
    conteo = ($fechacumple.next_year - hoy).to_i
  end
end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController

def new
    @contacto = Contacto.new
end

def create
  @contacto = Contacto.new(secure_params)
  if @contacto.valid?
     # Falta por salvar la data
     UsuarioCorreo.contacto_email(@contacto).deliver

     flash[:notice] = "Mensaje enviado de #{@contacto.nombre}."
     redirect_to root_path
  else
     render :new
  end
end

private #solo los metodos de la clase pueden acceder a lo que este aquí
 
 def secure_params
   params.require(:contacto).permit(:nombre, :email, :mensaje)
 end

end

app/controllers/visitantes_controller.rb
class VisitantesController < ApplicationController
  before_action :set_visitante, only: [:show, :edit, :update, :destroy]

  # GET /visitantes
  # GET /visitantes.json
  def index
    @visitante = Visitante.new
  end

  # GET /visitantes/1
  # GET /visitantes/1.json
  def show
  end

  # GET /visitantes/new
  def new
    Rails.logger.debug "DEBUG: entrando al método new"
    @visitante = Visitante.new
    Rails.logger.debug "DEBUG: Nombre del usuario" + @visitante.nombre
    flash[:notice] = 'Bienvenido!'
    flash[:alert] = 'Mi cumpleaños está cerca.'
    flash[:warnning] = 'CUIDADO!'
    flash[:sucess] = 'UPAAAAAA!'
  end

  # GET /visitantes/1/edit
  def edit
  end

  # POST /visitantes
  # POST /visitantes.json
  def create
    @visitante = Visitante.new(visitante_params)

    respond_to do |format|
      if @visitante.save
        format.html { redirect_to @visitante, notice: 'Visitante was successfully created.' }
        format.json { render :show, status: :created, location: @visitante }
      else
        format.html { render :new } #Carga de nuevo el formulario si hay error
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitantes/1
  # PATCH/PUT /visitantes/1.json
  def update
    respond_to do |format|
      if @visitante.update(visitante_params)
        format.html { redirect_to @visitante, notice: 'Visitante was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitante }
      else
        format.html { render :edit }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitantes/1
  # DELETE /visitantes/1.json
  def destroy
    @visitante.destroy
    respond_to do |format|
      format.html { redirect_to visitantes_url, notice: 'Visitante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitante
      @visitante = Visitante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitante_params
      params.fetch(:visitante, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
	def mensaje1
		"Gracias, Casique helper"
	end
end

app/views/contactos/new.html.erb
<% content_for :title do %>Contacto<% end %>

<h3>Contacto</h3>

<div class="form">
<%= simple_form_for @contacto do |f| %>


<%= f.input :nombre, label: 'Su nombre por favor',  error: 'El nombre de usuario es obligatorio'%>
<%= f.input :email, placeholder: 'user@domain.com' %>
<%= f.input :mensaje, as: :text %>

<%= f.button :submit, 'Enviar', class: 'submit' %>

<% end %>
</div> 

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%=link_to 'Home', root_path %></li>
  <li><%=link_to 'About', page_path("acercade")%></li>
  <li><%=link_to 'Contacto', new_contacto_path%></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mascotas" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mascotas" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/paginas/acercade.html.erb
<% content_for :title do %>Acerca de...<%end%>
<h3>Acerca de mascotas</h3>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/usuario_correo/contacto_email.html.erb
<!DOCTYPE html>
 <html>
   <head>
     <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
   </head>
   <body>
     <h1>Mascotas Contacto</h1>
     <p>Este visitante requiere contactarlo:</p>
<p><%= @contacto.nombre %><br/> <%= @contacto.email %><br/></p>
<p>El visitante dice:</p>
<p>"<%= @contacto.mensaje %>”</p>
 </body>
</html>

app/views/usuario_correo/contacto_email.txt.erb
Tu has recibido un mensaje de: <%= @contacto.nombre %> con el email: <%= @contacto.email %>.
EL visitante dijo:
"<%= @contact.mensaje %>"

app/views/visitantes/_form.html.erb
<%= form_for(@visitante) do |f| %>
  <% if @visitante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visitante.errors.count, "error") %> prohibited this visitante from being saved:</h2>

      <ul>
      <% @visitante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visitantes/edit.html.erb
<h1>Editing Visitante</h1>

<%= render 'form' %>

<%= link_to 'Show', @visitante %> |
<%= link_to 'Back', visitantes_path %>

app/views/visitantes/index.html.erb
<p id="notice"><%= notice %></p>

<h3>P&aacute;gina principal</h3>   
@visitante es una variable de instancia   
<p>Bienvenido a la página de: <%= @visitante.nombre %>.</p>   
<p>Yo nací el:<%= @visitante.fechacumple %>.</p>   
<p>y me quedan unicamente  <%= @visitante.conteo %> d&iacute;as para mi   
cumplea&ntilde;os!</p>

<h1>Listing Visitantes</h1>

<%if @visitantes!=nil%>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitantes.each do |visitante| %>
      <tr>
        <td><%= link_to 'Show', visitante %></td>
        <td><%= link_to 'Edit', edit_visitante_path(visitante) %></td>
        <td><%= link_to 'Destroy', visitante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%else%>
  <h5>No existen visitantes almacenados.</h5>
<%end%>

<%= link_to 'New Visitante', new_visitante_path %>

app/views/visitantes/new.html.erb
<%content_for :sidebar do %>
<h3>Información de contacto</h3>
<p>Email: carvel94ror@gmail.com</p>
<%end%>
<h1>New Visitante</h1>

<%= render 'form' %>

<%= link_to 'Back', visitantes_path %>

<%=mensaje1%>

app/views/visitantes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_visitante_path(@visitante) %> |
<%= link_to 'Back', visitantes_path %>